#!/bin/bash

target_table="library_call_analysis_dotnetlibraryclass"
temp_table="${target_table}_temp"
filename="system_class"

printf "\
CREATE TEMP TABLE ${temp_table} (\n\
   namespace character varying(255) NOT NULL,\n\
   classname character varying(255) NOT NULL,\n\
   function character varying(255) NOT NULL\n\
);\n\
\n\
\\copy ${temp_table} FROM '$(readlink -f ${filename}.dat)' WITH DELIMITER AS ' ';\n\
\n\
INSERT INTO ${target_table} (namespace, classname, function) SELECT * FROM ${temp_table};\
" > ../database/${filename}.sql
