#!/bin/bash

if [ -z "$1" ]
then
   dir=fix_commits
   mkdir -p $dir
else
   project=$(basename $(realpath $1))
   dir=$(realpath $(dirname $0))/../fix_commits/$project
   mkdir -p $dir
   cd $1
fi

cores=$(grep -c processor /proc/cpuinfo)

for i in $(git log --pretty=oneline | grep -Ei "fix|bug|patch" | grep -Ev '^\S* \bMerge\b' | sed -rn "s/^(\S*) .*/\1/p"); do
   git show $i > $dir/$i &
   joblist=($(jobs -p))
   while (( ${#joblist[*]} >= $cores ))
   do
      sleep 0.001
      joblist=($(jobs -p))
   done
done
wait
