#!/bin/bash

if [ -z "$1" ]
then
   dir=fix_commits
   mkdir $dir 2>/dev/null
else
   project=$(basename $(realpath $1))
   dir=$(realpath $PWD)/${project}_fix_commits
   mkdir $dir 2>/dev/null
   cd $1
fi



for i in $(git log --grep='fix' | sed -rn "s/^commit (\S*)/\1/p"); do
   git show $i > $dir/$i;
done
