#!/bin/bash

if [ -z "$1" ]
then
   dir=fix_commits
   mkdir -p $dir
else
   project=$(basename $(realpath $1))
   dir=$(realpath $(dirname $0))/../fix_commits/$project
   mkdir -p $dir
   cd $1
fi


for i in $(git log --pretty=oneline | grep fix | grep -E -v '^\S* \bMerge\b' | sed -rn "s/^(\S*) .*/\1/p"); do
   git show $i > $dir/$i &
done
wait
