#!/bin/bash

dirname=$(dirname $0)

this_project=$(basename $(realpath $dirname/..))

cd $dirname/..

for i in $dirname/../../*; do
   if [ "$(basename $i)" == "$this_project" ]; then
      continue
   fi
   script/get_git_fix_commit $i
done
