#!/bin/bash

if [ $# -eq 0 ] 
then
   echo "Please provide the directory"
   exit -1
fi

for i in $1/*/
do
   proj=$(basename $i) 
   echo "Analyzing project $proj"
   psql -d bugfixlearning -c "select library_call_analysis_analyze_function_calls('$proj')" > $proj.txt &
done
wait
echo "Done"
